In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [15]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [19]:
#dimension
b.ndim

2

In [20]:
#Shape
a.shape

(3,)

In [22]:
#Data type
b.dtype

dtype('float64')

In [26]:
#Size (bytes)
b.itemsize


8

In [30]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
#GEt element at [r,c]
a[1][2]

[[1 2 3]
 [4 5 6]]


6

In [37]:
#Specific row/column
a[0,:]
a[0, 1::1]

array([2, 3])